/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: bgprow.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "bgprow.pb-c.h"
void   bgpcell__init
                     (BGPCell         *message)
{
  static BGPCell init_value = BGPCELL__INIT;
  *message = init_value;
}
size_t bgpcell__get_packed_size
                     (const BGPCell *message)
{
  assert(message->base.descriptor == &bgpcell__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bgpcell__pack
                     (const BGPCell *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bgpcell__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bgpcell__pack_to_buffer
                     (const BGPCell *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bgpcell__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BGPCell *
       bgpcell__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BGPCell *)
     protobuf_c_message_unpack (&bgpcell__descriptor,
                                allocator, len, data);
}
void   bgpcell__free_unpacked
                     (BGPCell *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bgpcell__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   bgprow__init
                     (BGPRow         *message)
{
  static BGPRow init_value = BGPROW__INIT;
  *message = init_value;
}
size_t bgprow__get_packed_size
                     (const BGPRow *message)
{
  assert(message->base.descriptor == &bgprow__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t bgprow__pack
                     (const BGPRow *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &bgprow__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t bgprow__pack_to_buffer
                     (const BGPRow *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &bgprow__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
BGPRow *
       bgprow__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (BGPRow *)
     protobuf_c_message_unpack (&bgprow__descriptor,
                                allocator, len, data);
}
void   bgprow__free_unpacked
                     (BGPRow *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &bgprow__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor bgpcell__field_descriptors[2] =
{
  {
    "PeerId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(BGPCell, peerid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ASPath",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BGPCell, aspath),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bgpcell__field_indices_by_name[] = {
  1,   /* field[1] = ASPath */
  0,   /* field[0] = PeerId */
};
static const ProtobufCIntRange bgpcell__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bgpcell__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BGPCell",
  "BGPCell",
  "BGPCell",
  "",
  sizeof(BGPCell),
  2,
  bgpcell__field_descriptors,
  bgpcell__field_indices_by_name,
  1,  bgpcell__number_ranges,
  (ProtobufCMessageInit) bgpcell__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor bgprow__field_descriptors[2] =
{
  {
    "Pfx",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(BGPRow, pfx),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "Cells",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(BGPRow, n_cells),
    offsetof(BGPRow, cells),
    &bgpcell__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned bgprow__field_indices_by_name[] = {
  1,   /* field[1] = Cells */
  0,   /* field[0] = Pfx */
};
static const ProtobufCIntRange bgprow__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor bgprow__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "BGPRow",
  "BGPRow",
  "BGPRow",
  "",
  sizeof(BGPRow),
  2,
  bgprow__field_descriptors,
  bgprow__field_indices_by_name,
  1,  bgprow__number_ranges,
  (ProtobufCMessageInit) bgprow__init,
  NULL,NULL,NULL    /* reserved[123] */
};
