/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: peer.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "peer.pb-c.h"
void   peer__init
                     (Peer         *message)
{
  static Peer init_value = PEER__INIT;
  *message = init_value;
}
size_t peer__get_packed_size
                     (const Peer *message)
{
  assert(message->base.descriptor == &peer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t peer__pack
                     (const Peer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &peer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t peer__pack_to_buffer
                     (const Peer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &peer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Peer *
       peer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Peer *)
     protobuf_c_message_unpack (&peer__descriptor,
                                allocator, len, data);
}
void   peer__free_unpacked
                     (Peer *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &peer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor peer__field_descriptors[4] =
{
  {
    "peerid_orig",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Peer, peerid_orig),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collector_str",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Peer, collector_str),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_ip_addr",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Peer, peer_ip_addr),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "peer_asnumber",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Peer, peer_asnumber),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned peer__field_indices_by_name[] = {
  1,   /* field[1] = collector_str */
  3,   /* field[3] = peer_asnumber */
  2,   /* field[2] = peer_ip_addr */
  0,   /* field[0] = peerid_orig */
};
static const ProtobufCIntRange peer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor peer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Peer",
  "Peer",
  "Peer",
  "",
  sizeof(Peer),
  4,
  peer__field_descriptors,
  peer__field_indices_by_name,
  1,  peer__number_ranges,
  (ProtobufCMessageInit) peer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
